workflows:
  android-debug:
    name: ComTac v14 Android (Standalone APK)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.tactical.comtac"
    
    scripts:
      - name: Install Dependencies
        script: | 
          rm -rf node_modules
          rm -f package-lock.json
          npm install --legacy-peer-deps
          npx expo install --fix

      - name: Expo Prebuild
        script: | 
          npx expo prebuild --platform android --clean

      - name: Force Bundle JS (Correction Ecran Rouge)
        script: | 
          # 1. On crée le dossier qui va recevoir le code compilé
          mkdir -p android/app/src/main/assets
          
          # 2. On compile manuellement le JS pour le mettre DANS l'app
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.tsx \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew
          # On compile l'APK qui contient maintenant le bundle
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - nicolas.maheux45@gmail.com
        notify:
          success: true
          failure: true
